
persistence:
    enabled: true
    #existingGiteaClaim: gitea-gitea
    #existingPostgresClaim: gitea-postgres
    giteaSize: 10Gi
    postgresSize: 5Gi
    storageClass: gp2
    accessMode: ReadWriteMany
