
persistence:
    enabled: true
    #existingGiteaClaim: gitea-gitea
    #existingPostgresClaim: gitea-postgres
    giteaSize: 10Gi
    postgresSize: 5Gi
#    storageClass: default
    accessMode: ReadWriteOnce
